### PR TITLE
Blocking execution

### PR DESCRIPTION
**Pull request by rik-bos**
Hi Andries,

In multiple projects I run into the issue that the Microflow timer triggers a microflow even if the previous execution isn't finished. Ultimately this can crash an entire app since the timers might just "ddos" the app by adding more requests even if the server is already low on memory.

I changed it so it won't trigger a new flow before the last one is finished (just like Scheduled Events work).

Can you merge this change and publish a new version in the appstore?

Rik

### CODE REVIEW

**Comment by diego-antonelli** [comment]
@rik-bos can you please bump the version of this widget?

**Review by leonardomendix — APPROVED** [review]
Tested and it works as expected.

**Review by diego-antonelli — APPROVED** [review]

**Comment by rik-bos** [comment]
Hi Diego,

Thanks for picking this up! I saw that you already merged the PR. Is it still needed for me to bump the version?

Rik

**Comment by diego-antonelli** [comment]
No, there is another PR we will merge and that one contains a bump. I am just waiting the PR to be rebased

**Pull request merged**
